### ISSUE TITLE
Пустые блоки catch

### ISSUE THREAD

**Issue by anry-das** [Alenka-K/NCTaskManager#13]
В коде встречаются пустые блоки catch, что крайне неправильно. В них необходимо добавить как минимум логгирование.
Также можно объеденить одинаковые блоки catch (например, в классе TaskIO)

**Comment by Alenka-K** [comment]
Перепроверила код - пустых блоков catch не обнаружила (но они есть в папке test). 
Одинаковые блоки catch  в классе TaskIO объединила.
28146d4ab567cc10bca56999b023da65e9689a34

**Comment by anry-das** [comment]
Да, действительно. Недосмотрел :-)
